#Environment parameters
ENVIRONMENT : "InvertedPendulum-v5"
RENDER : "no"
RENDER_MODE : "human"
NORMAL_ENV: ["Pendulum-v1", "InvertedPendulum-v5", "Pusher-v5"]
INPUT_FEATURES: 0
ACTION_SPACE: 0

#Train Parameters
EPISODES : 1000
EARLY_STOP : 9300
SEED : 0
DEVICE : "cuda"

#hyperparameters
LR : 0.0001
ENTROPY_START: 0.35
ENTROPY_END : 0.02
DISCOUNT_FACTOR :  0.99
BUFFER_SIZE: 100000
BATCH_SIZE : 1024
TAU : 0.05

#Neural Network
CLIP: 0.5
HIDDEN_LAYERS:
  - 1024
  - 1024

#Memory
#simple, per, ucb, delta-dep
TRAIN_MODE : "ucb"
PER_ALPHA: 1.0
INIT_TD_ERROR: 0.00000001   #per
INIT_WEIGHT : 1.0           #per
CP : 0.31                 #ucb