ENVIRONMENT : "BipedalWalker-v3"
RENDER : "no"
RENDER_MODE : "human"
EPISODE_STOP : 1600
EPISODES : 4000
EARLY_STOP : 3000
LR : 0.0005
ENTROPY_COEFFICIENT : 0.01
DISCOUNT_FACTOR : 0.99
TRAIN_MODE : "simple"
BUFFER_SIZE : 10000
BATCH_SIZE : 256
DEVICE : "cuda"
PER_ALPHA: 1.0
BETA : 0.5
TAU : 0.005
SEED : 0