ENVIRONMENT : "Ant-v5"
RENDER_MODE : "rgb_array"
EPISODE_STOP : 1000
EPISODES : 1000
LR : 0.0003
DISCOUNT_FACTOR : 0.99
TRAIN_MODE : "simple"
BUFFER_SIZE : 50000
BATCH_SIZE : 512
DEVICE : "cuda"
PER_ALPHA: 1.0
BETA : 0.5
TAU : 0.005
SEED : 0