#Environment parameters
ENVIRONMENT : "InvertedPendulum-v5"
RENDER : "no"
RENDER_MODE : "human"
NORMAL_ENV: ["Pendulum-v1", "InvertedPendulum-v5", "Pusher-v5"]
INPUT_FEATURES: 0
ACTION_SPACE: 0

#Train Parameters
EPISODES : 3000
EARLY_STOP : 9300
SEED : 42
DEVICE : "cuda"

#hyperparameters
LR : 0.0003
ENTROPY_START: 0.2
ENTROPY_END : 0.01
DISCOUNT_FACTOR : 0.99
BUFFER_SIZE: 200000
BATCH_SIZE : 256
TAU : 0.05

#Neural Network
HIDDEN_LAYERS: 128

#Memory
TRAIN_MODE : "simple"
INIT_TD_ERROR: 0.0001  #per
INIT_WEIGHT : 0.01     #per
CP : 0.5               #ucb