ENVIRONMENT : "Ant-v5"
RENDER_MODE : "rgb_array"
EPISODE_STOP : 1000
EPISODES : 2000
LR : 0.0003
ENTROPY_COEFFICIENT : 0.002
DISCOUNT_FACTOR : 0.99
TRAIN_MODE : "simple"
BUFFER_SIZE : 100000
BATCH_SIZE : 1024
DEVICE : "cuda"
PER_ALPHA: 1.0
BETA : 0.5
TAU : 0.005
SEED : 0