ENVIRONMENT : "Pusher-v5"
RENDER : "no"
RENDER_MODE : "human"
NORMAL_ENV: ["Pendulum-v1", "InvertedPendulum-v5", "Pusher-v5"]
EPISODES : 3000
EARLY_STOP : 10000
HIDDEN_LAYERS: 256
LR : 0.001
ENTROPY_COEFFICIENT : 0.06
DISCOUNT_FACTOR : 0.99
TRAIN_MODE : "simple"
BUFFER_SIZE : 100000
BATCH_SIZE : 1024
DEVICE : "cuda"
PER_ALPHA: 1.0
BETA : 0.5
TAU : 0.05
SEED : 42