ENVIRONMENT : "Reacher-v5"
RENDER : "yes"
RENDER_MODE : "human"
EPISODES : 2000
EARLY_STOP : 10000
HIDDEN_LAYERS: 128
LR : 0.0005
ENTROPY_COEFFICIENT : 0.03
DISCOUNT_FACTOR : 0.99
TRAIN_MODE : "simple"
BUFFER_SIZE : 10000
BATCH_SIZE : 1024
DEVICE : "cuda"
PER_ALPHA: 1.0
BETA : 0.5
TAU : 0.05
SEED : 42