ENVIRONMENT : "Pendulum-v1"
RENDER : "no"
RENDER_MODE : "human"
EPISODES : 2000
EARLY_STOP : 9300
HIDDEN_LAYERS: 256
LR : 0.001
ENTROPY_COEFFICIENT : 0.01
DISCOUNT_FACTOR : 0.99
TRAIN_MODE : "simple"
BUFFER_SIZE : 100000
BATCH_SIZE : 256
DEVICE : "cuda"
PER_ALPHA: 1.0
BETA : 0.5
TAU : 0.005
SEED : 42