#Environment parameters
ENVIRONMENT : "Pendulum-v1"
RENDER : "no"
RENDER_MODE : "human"
NORMAL_ENV: ["Pendulum-v1", "InvertedPendulum-v5", "Pusher-v5"]

#Train Parameters
EPISODES : 3000
EARLY_STOP : 3600
SEED : 42
DEVICE : "cuda"

#hyperparameters
LR : 0.0001
ENTROPY_START: 0.1
ENTROPY_END : 0.01
DISCOUNT_FACTOR : 0.99
BUFFER_SIZE: 200000
BATCH_SIZE : 128
TAU : 0.05

#Neural Network
HIDDEN_LAYERS: 128

#Memory
TRAIN_MODE : "per"
INIT_TD_ERROR: 0.001  #per
INIT_WEIGHT : 0.01    #per
CP : 0                #ucb