#Environment parameters
ENVIRONMENT : "Pendulum-v1"
RENDER : "no"
RENDER_MODE : "human"
NORMAL_ENV: ["Pendulum-v1", "InvertedPendulum-v5", "Pusher-v5"]
INPUT_FEATURES: 0
ACTION_SPACE: 0

#Train Parameters
EPISODES : 1000
EARLY_STOP : 9300
SEED : 0
DEVICE : "cuda"

#hyperparameters
LR : 0.0005
ENTROPY_START: 0.2
ENTROPY_END : 0.001
DISCOUNT_FACTOR :  0.99
BUFFER_SIZE: 120000
BATCH_SIZE : 512
TAU : 0.05

#Neural Network
CLIP: 0.5
HIDDEN_LAYERS:
  - 128
  - 128

#Memory
TRAIN_MODE : "per"
PER_ALPHA: 0.6
INIT_TD_ERROR: 0.00000001   #per
INIT_WEIGHT : 1.0           #per
CP : 0.24                 #ucb