ENVIRONMENT : "InvertedDoublePendulum-v5"
RENDER : "no"
RENDER_MODE : "human"
EPISODE_STOP : 1000
EPISODES : 2000
EARLY_STOP : 9300
LR : 0.002
ENTROPY_COEFFICIENT : 0.07
DISCOUNT_FACTOR : 0.99
TRAIN_MODE : "simple"
BUFFER_SIZE : 10000
BATCH_SIZE : 1024
DEVICE : "cuda"
PER_ALPHA: 1.0
BETA : 0.5
TAU : 0.005
SEED : 0