ENVIRONMENT : "InvertedDoublePendulum-v5"
RENDER : "no"
RENDER_MODE : "human"
EPISODE_STOP : 1600
EPISODES : 2000
END_TRAINING : 300
LR : 0.001
ENTROPY_COEFFICIENT : 0.05
DISCOUNT_FACTOR : 0.99
TRAIN_MODE : "simple"
BUFFER_SIZE : 100000
BATCH_SIZE : 512
DEVICE : "cuda"
PER_ALPHA: 1.0
BETA : 0.5
TAU : 0.005
SEED : 0