#Environment parameters
ENVIRONMENT : "Reacher-v5"
RENDER : "no"
RENDER_MODE : "human"
NORMAL_ENV: ["Pendulum-v1", "InvertedPendulum-v5", "Pusher-v5"]
INPUT_FEATURES: 0
ACTION_SPACE: 0

#Train Parameters
EPISODES : 5000
EARLY_STOP : 6000
SEED : 52
DEVICE : "cuda"

#hyperparameters
LR : 0.0001
ENTROPY_START: 0.1
ENTROPY_END : 0.001
DISCOUNT_FACTOR : 0.98
BUFFER_SIZE: 250000
BATCH_SIZE : 512
TAU : 0.005

#Neural Network
HIDDEN_LAYERS:
  - 256
  - 256
  - 128

#Memory
TRAIN_MODE : "per"
INIT_TD_ERROR: 0.00000001   #per
INIT_WEIGHT : 1.0           #per
CP : 0.1                   #ucb