#Environment parameters
ENVIRONMENT : "HalfCheetah-v5"
RENDER : "no"
RENDER_MODE : "human"
NORMAL_ENV: ["Pendulum-v1", "InvertedPendulum-v5", "Pusher-v5"]
INPUT_FEATURES: 0
ACTION_SPACE: 0

#Train Parameters
EPISODES : 5000
EARLY_STOP : 9300
SEED : 0
DEVICE : "cuda"

#hyperparameters
LR : 0.001
ENTROPY_START: 0.75
ENTROPY_END : 0.001
DISCOUNT_FACTOR : 0.99
BUFFER_SIZE: 120000
BATCH_SIZE : 512
TAU : 0.05

#Neural Network
HIDDEN_LAYERS: 128

#Memory
TRAIN_MODE : "ucb"
INIT_TD_ERROR: 0.00000001   #per
INIT_WEIGHT : 1.0           #per
CP : 0.3                   #ucb