ENVIRONMENT : "InvertedPendulum-v5"
RENDER : "no"
RENDER_MODE : "human"
NORMAL_ENV: ["Pendulum-v1", "InvertedPendulum-v5", "Pusher-v5"]
EPISODES : 3000
EARLY_STOP : 3600
HIDDEN_LAYERS: 512
LR : 0.0001
ENTROPY_START: 0.1
ENTROPY_END : 0.01
DISCOUNT_FACTOR : 0.99
TRAIN_MODE : "simple"
BUFFER_SIZE: 200000
BATCH_SIZE : 1024
DEVICE : "cuda"
PER_ALPHA: 1.0
BETA : 0.5
TAU : 0.05
SEED : 42