#Environment parameters
ENVIRONMENT : "Pendulum-v1"
RENDER : "no"
RENDER_MODE : "human"
NORMAL_ENV: ["Pendulum-v1", "InvertedPendulum-v5", "Pusher-v5"]
INPUT_FEATURES: 0
ACTION_SPACE: 0

#Train Parameters
EPISODES : 3000
EARLY_STOP : -118
SEED : 42
DEVICE : "cuda"

#hyperparameters
LR : 0.0001
ENTROPY_START: 0.1
ENTROPY_END : 0.01
DISCOUNT_FACTOR : 0.99
BUFFER_SIZE: 10000
BATCH_SIZE : 512
TAU : 0.05

#Neural Network
HIDDEN_LAYERS: 256

#Memory
TRAIN_MODE : "ucb"
INIT_TD_ERROR: 0.001  #per
INIT_WEIGHT : 0.01    #per
CP : 0.4              #ucb